#!/bin/bash

set -o errexit
set -o pipefail

source .env

function ps {
    docker compose ps
}

function up {
    docker compose up -d "${@}"
}

function down {
    docker compose down "${@}"
}

function composer {
    docker run --rm --interactive \
        -e COMPOSER_CACHE_DIR="/app/.cache/composer" \
        -u "$(id -u):$(id -g)" -v "$(pwd):/app" \
        -w /app composer:2.7.2 composer "${@}"
}

function nginx:check {
    docker compose exec nginx nginx -t
}

function nginx:status {
    docker compose exec nginx service nginx status
}

function nginx:reload {
    docker compose exec web nginx -s reload
}

function php:console {
    docker compose exec php php -a
}

function test {
    TEST_PATH="${@:-tests}"
    docker compose exec app ./vendor/bin/phpunit --colors ${TEST_PATH}
}

function codecept {
    docker compose run --rm php_test ./vendor/bin/codecept ${@}
}

function phpcs {
    TEST_PATH="${@:-.}"
    ./vendor/bin/phpcs --standard=.phpcs.xml src tests ${TEST_PATH}
}

function phpcbf {
    TEST_PATH="${@:-.}"
        ./vendor/bin/phpcbf ${TEST_PATH}
}

function phpstan {
    TEST_PATH="${@:-}"
    ./vendor/bin/phpstan analyse --memory-limit 1G ${TEST_PATH}
}

function phpfmt {
    TEST_PATH="${@:-.}"
    ./vendor/bin/php-cs-fixer fix ${TEST_PATH}
}

function phpmd {
    TEST_PATH="${@:-.}"
   ./vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode
}

function git:clean:branchs {
    git branch | grep -v '\*\|master\|main\|develop\|production' | xargs -n 1 git branch -D
}

function db:console {
    docker compose exec db sh -c "MYSQL_PWD=${DB_PASSWORD} mysql -u ${DB_USERNAME} ${DB_DATABASE} --default-character-set utf8mb4"
}

function db:reset {
    docker compose cp database/schema.sql db:/tmp/
    docker compose exec db sh -c "MYSQL_PWD=${DB_PASSWORD} mysql -u ${DB_USERNAME} ${DB_DATABASE} --default-character-set utf8mb4 < /tmp/schema.sql"
}

function db:populate {
    docker compose exec php php database/Populate/populate.php
}

TIMEFORMAT=$'\nTask completed in %3lR'
time ${@}